#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server
# so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script

sudo apt-get update
sudo apt-get install haproxy -y

# Configure HAProxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http-in
        bind *:80
        default_backend servers
backend servers
        balance roundrobin
        server web-01 54.152.134.92:80 check
        server web-02 54.172.230.218:80 check
EOT

# start HAProxy
sudo /etc/init.d/haproxy start

# set HAProxy to start on boot
sudo update-rc.d haproxy defaults

# reload HAProxy configuration
sudo /etc/init.d/haproxy reload
