#!/usr/bin/env bash
# Crée une paire de clés RSA avec un nom de clé privée "school"
# La clé doit avoir 4096 bits et être protégée par la passphrase "betty"

ssh-keygen -t rsa -b 4096 -f school -N "betty"
